title_fr: drivemeup covoiturage
title_en: drivemeup carpooling
permalink: /:categories/:year/:month/:day/:title
markdown: maruku
description_fr: "Trouvez des annonces de covoiturage gratuitement."
description_en: "Find carpools or rides for free."
keywords_fr: "covoiturage,annonce covoiturage,co voiturage,co-voiturage,voiturage,covoiturage paris,covoiturage gratuit,covoiturage france,covoiturage voyage,voiturage,trajets,autopartage,carrefour"
keywords_en: "carpool, rideshare, carpooling, ridesharing, ride, share, ride share, transportation, transportation alternatives, corporate, company, enterprise, city, local, commuter, commute, long distance, travel, car, event, events, free, carpools, rideshares, road trip, carsharing, car share, together, map, ride, rider, car pool, driver, hitchhike, HOV, free, university, college, school, campus, event, events"